version: 3.0.{build}
configuration: Debug
platform: Any CPU
assembly_info:
  patch: true
  file: '**\GlobalAssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: Loki.sln
  verbosity: minimal
test:
  assemblies:
  - Loki.Core.Tests.dll
  - Loki.UI.Test.dll