//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loki.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loki.Core.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid exception type : {0}.
        /// </summary>
        internal static string Error_InvalidExceptionType {
            get {
                return ResourceManager.GetString("Error_InvalidExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy index is out of range..
        /// </summary>
        internal static string Utils_BaseDictionary_CopyIndexOutOfRange {
            get {
                return ResourceManager.GetString("Utils_BaseDictionary_CopyIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination array must not be null..
        /// </summary>
        internal static string Utils_BaseDictionary_CopyNullDest {
            get {
                return ResourceManager.GetString("Utils_BaseDictionary_CopyNullDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination array is not large enough. Check array.Length and arrayIndex..
        /// </summary>
        internal static string Utils_BaseDictionary_CopySmallDest {
            get {
                return ResourceManager.GetString("Utils_BaseDictionary_CopySmallDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No parameterless constructor for Type {0}..
        /// </summary>
        internal static string Utils_ExpressionHelper_NoConstructor {
            get {
                return ResourceManager.GetString("Utils_ExpressionHelper_NoConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No component for metadata {0}..
        /// </summary>
        internal static string Utils_ExtensionManager_Component {
            get {
                return ResourceManager.GetString("Utils_ExtensionManager_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toolkit is not initialized..
        /// </summary>
        internal static string Utils_Toolkit_NotInitialized {
            get {
                return ResourceManager.GetString("Utils_Toolkit_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key musn&apos;t be null..
        /// </summary>
        internal static string Utils_WeakDictionnay_KeyNullException {
            get {
                return ResourceManager.GetString("Utils_WeakDictionnay_KeyNullException", resourceCulture);
            }
        }
    }
}
