//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loki.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loki.Core.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid exception type : {0}.
        /// </summary>
        internal static string Error_InvalidExceptionType {
            get {
                return ResourceManager.GetString("Error_InvalidExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy index is out of range..
        /// </summary>
        internal static string Utils_BaseDictionary_CopyIndexOutOfRange {
            get {
                return ResourceManager.GetString("Utils_BaseDictionary_CopyIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination array must not be null..
        /// </summary>
        internal static string Utils_BaseDictionary_CopyNullDest {
            get {
                return ResourceManager.GetString("Utils_BaseDictionary_CopyNullDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination array is not large enough. Check array.Length and arrayIndex..
        /// </summary>
        internal static string Utils_BaseDictionary_CopySmallDest {
            get {
                return ResourceManager.GetString("Utils_BaseDictionary_CopySmallDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameterless constructor for Type {0}..
        /// </summary>
        internal static string Utils_ExpressionHelper_NoConstructor {
            get {
                return ResourceManager.GetString("Utils_ExpressionHelper_NoConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No component for metadata {0}..
        /// </summary>
        internal static string Utils_ExtensionManager_Component {
            get {
                return ResourceManager.GetString("Utils_ExtensionManager_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit is not initialized..
        /// </summary>
        internal static string Utils_Toolkit_NotInitialized {
            get {
                return ResourceManager.GetString("Utils_Toolkit_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key musn&apos;t be null..
        /// </summary>
        internal static string Utils_WeakDictionnay_KeyNullException {
            get {
                return ResourceManager.GetString("Utils_WeakDictionnay_KeyNullException", resourceCulture);
            }
        }
    }
}
