//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 06/27/2016 23:06:39
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Loki.Core.Resources
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Errors
    {
        
        private static ResourceLoader resourceLoader;
        
        static Errors()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Errors).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Errors");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Errors");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Invalid exception type : {0}"
        /// </summary>
        public static string Error_InvalidExceptionType
        {
            get
            {
                return resourceLoader.GetString("Error_InvalidExceptionType");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Copy index is out of range."
        /// </summary>
        public static string Utils_BaseDictionary_CopyIndexOutOfRange
        {
            get
            {
                return resourceLoader.GetString("Utils_BaseDictionary_CopyIndexOutOfRange");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Destination array must not be null."
        /// </summary>
        public static string Utils_BaseDictionary_CopyNullDest
        {
            get
            {
                return resourceLoader.GetString("Utils_BaseDictionary_CopyNullDest");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Destination array is not large enough. Check array.Length and arrayIndex."
        /// </summary>
        public static string Utils_BaseDictionary_CopySmallDest
        {
            get
            {
                return resourceLoader.GetString("Utils_BaseDictionary_CopySmallDest");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No parameterless constructor for Type {0}."
        /// </summary>
        public static string Utils_ExpressionHelper_NoConstructor
        {
            get
            {
                return resourceLoader.GetString("Utils_ExpressionHelper_NoConstructor");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No component for metadata {0}."
        /// </summary>
        public static string Utils_ExtensionManager_Component
        {
            get
            {
                return resourceLoader.GetString("Utils_ExtensionManager_Component");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Toolkit is not initialized."
        /// </summary>
        public static string Utils_Toolkit_NotInitialized
        {
            get
            {
                return resourceLoader.GetString("Utils_Toolkit_NotInitialized");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Key musn't be null."
        /// </summary>
        public static string Utils_WeakDictionnay_KeyNullException
        {
            get
            {
                return resourceLoader.GetString("Utils_WeakDictionnay_KeyNullException");
            }
        }
    }
}
